#!/usr/bin/env bash
# Make sure this file has a executable bit (e.g. chmod +x)


source {{ CONFIG_GEN_GENERATED_DIR }}/.env/bin/activate
cd {{ CONFIG_GEN_GENERATED_DIR }}
rm -f {{ CONFIG_GEN_LOGS_DIR }}/django.pid


exec envuidgid {{ EFFECTIVE_USER }} python manage.py run_gunicorn \
    --workers=3                                             \
    --user={{ EFFECTIVE_USER }}                             \
    --group={{ EFFECTIVE_USER }}                            \
    --bind=localhost:9000                                   \
    --max-requests=1024                                     \
    --pid={{ CONFIG_GEN_LOGS_DIR }}/django.pid              \
    --log-file={{ CONFIG_GEN_LOGS_DIR }}/django.log
